version: '3'
services:
  nuxt-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: bitcoin_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - '3306:3306'